source 'https://github.com/CocoaPods/Specs.git'

target 'KZBootstrap' do
  pod 'AFNetworking', '~> 2.4.1'

  pod "KZBootstrap", :path => "../"
  pod "KZBootstrap/Logging", :path => "../"
  pod "KZBootstrap/Debug", :path => "../"
end
